name: CD Pipeline

on:
  workflow_run:
    workflows: ["CD Pipeline"]
    types: [completed]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: |
        sudo docker pull razmiqayelyan/cicd-pipeline:latest

    - name: Delete Old Docker container
      run: |
        sudo docker rm -f cicd-pipeline-container || true

    - name: Run Docker Container
      run: |
        sudo docker run -d -p 8080:8080 --name cicd-pipeline-container razmiqayelyan/cicd-pipeline:latest
